version: '2.1'

services:
  keycloak:
    image: entando/keycloak
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: qwe123
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      DB_USER: keycloak
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"
