version: '3.3'

services:
  keycloak:
    build:
        context: ./
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: qwe123
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_DEFAULT_THEME: "entando"