apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: entando/entando-keycloak
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
  - name: keycloak
    build:
      artifacts:
        - image: entando/entando-keycloak
          docker:
            dockerfile: Dockerfile.keycloak
            buildArgs:
              VERSION: '{{.VERSION}}'
  - name: redhat-sso
    build:
      artifacts:
        - image: entando/entando-redhat-sso
          docker:
            dockerfile: Dockerfile.redhat-sso
            buildArgs:
              VERSION: '{{.VERSION}}'
